env:
  TERM: xterm-256color

font:
  # Point size
  size: 12
  # The normal (roman) font face to use.
  normal:
    family: 'DejaVuSansM Nerd Font Mono'

  # The bold font face
  bold:
    family: 'DejaVuSansM Nerd Font Mono'

  # The italic font face
  italic:
    family: 'DejaVuSansM Nerd Font Mono'

colors:
  # Default colors
  primary:
    background: '#282c34'
